# Generated by Django 5.2 on 2026-07-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participats',
            new_name='participants',
        ),
    ]
